jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-package: jdk
        java-version: '20'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build and test with Maven
      run: ./mvnw -B package
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: SonarCloud Scan
      run: ./mvnw -B org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=mediathekview_MediathekView
        -Dsonar.organization=mediathekview -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=$SONAR_TOKEN
name: Build and test
on:
  repository_dispatch:
    types: trigger-ga___build.yml
