jobs:
  build:
    if: needs.test.outputs.haschanged == 'true'
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        ref: develop
    - continue-on-error: true
      name: Set up JDK 20
      uses: actions/setup-java@v1
      with:
        java-version: 20
    - continue-on-error: true
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        targets: INSTALL4J_JAVA_HOME
        version: '8'
    - continue-on-error: true
      name: Download install4j
      uses: wei/curl@v1
      with:
        args: -fsSL 'https://download-gcdn.ej-technologies.com/install4j/install4j_unix_9_0_7.tar.gz'
          --output install4j.tar.gz
    - continue-on-error: true
      name: Extract install4j
      run: tar -zxvf install4j.tar.gz
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        LICENSE_KEY_9: ${{ secrets.LICENSE_KEY_9 }}
      name: Add install4j license
      run: ./mvnw clean install4j:install-license -Pinstall4j
    - continue-on-error: true
      uses: actions/download-artifact@v2
      with:
        name: target
    - continue-on-error: true
      name: Building ${{ matrix.os }} ${{ matrix.architecture }} with Maven
      run: ./mvnw -B package -P${{ matrix.maven_profiles }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - continue-on-error: true
      if: matrix.os == 'linux'
      name: Building AppImage
      run: scripte/appimage.sh
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: release-target
        path: 'target/media/

          target/*.AppImage

          '
    strategy:
      matrix:
        include:
        - architecture: 64bit
          maven_profiles: linux_64bit,install4j
          os: linux
        - architecture: 64bit
          maven_profiles: '!linux_64bit,linux_arm_64bit,install4j'
          os: arm
        - architecture: 64bit
          maven_profiles: '!linux_64bit,windows_64bit,install4j'
          os: windows
        - architecture: 64bit
          maven_profiles: '!linux_64bit,mac_intel'
          os: macOS
  test:
    outputs:
      haschanged: ${{steps.check-if-changed.outputs.changed}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
        ref: develop
    - continue-on-error: true
      id: check-if-changed
      uses: marceloprado/has-changed-path@v1
      with:
        paths: .github/workflows src/ res/ pom.xml .install4j/ .mvn/
    - continue-on-error: true
      if: steps.check-if-changed.outputs.changed == 'true'
      name: Set up JDK 20
      uses: actions/setup-java@v1
      with:
        java-version: 20
    - continue-on-error: true
      if: steps.check-if-changed.outputs.changed == 'true'
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      if: steps.check-if-changed.outputs.changed == 'true'
      name: Build and test with Maven
      run: ./mvnw -B package
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: steps.check-if-changed.outputs.changed == 'true'
      name: SonarCloud Scan
      run: ./mvnw -B org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=mediathekview_MediathekView
        -Dsonar.organization=mediathekview -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=$SONAR_TOKEN
name: Nigthly release
on:
  repository_dispatch:
    types: trigger-ga___nightly.yml
